CREATE DATABASE IF NOT EXISTS phalerum;
USE phalerum;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
DROP TABLE IF EXISTS agents;
DROP TABLE IF EXISTS audit;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS job_output;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS permission_lookup;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS role_lookup;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_auth;
CREATE TABLE `agents` (  `id` int NOT NULL,  `agent_name` varchar(256) NOT NULL,  `added_by` int NOT NULL,  `last_check_in` datetime DEFAULT NULL,  `ip_address` varchar(16) DEFAULT NULL,  `master` tinyint(1) NOT NULL DEFAULT '0',  `communication_token` json NOT NULL,  `os` varchar(128) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `audit` (  `id` int NOT NULL,  `user_id` int NOT NULL,  `action` varchar(256) NOT NULL,  `completed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `jobs` (  `id` int NOT NULL,  `job_name` varchar(256) NOT NULL,  `job_description` varchar(256) NOT NULL,  `completed` tinyint(1) NOT NULL DEFAULT '0',  `disabled` tinyint(1) NOT NULL DEFAULT '0',  `cross_compatible` tinyint(1) NOT NULL DEFAULT '0',  `os` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,  `agent_id` int NOT NULL DEFAULT '0',  `master_job` tinyint(1) NOT NULL DEFAULT '0',  `shell_command` tinyint(1) NOT NULL DEFAULT '0',  `command` varchar(512) DEFAULT NULL,  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `created_by` int NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `job_output` (  `job_id` int NOT NULL,  `output` varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,  `success` tinyint(1) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `permissions` (  `id` int NOT NULL,  `action` varchar(64) NOT NULL,  `description` varchar(256) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `permission_lookup` (  `role_id` int NOT NULL,  `permission_id` int NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `roles` (  `id` int NOT NULL,  `name` varchar(64) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `role_lookup` (  `user_id` int NOT NULL,  `role_id` int NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (  `id` int NOT NULL,  `username` varchar(256) NOT NULL,  `email_address` varchar(256) NOT NULL,  `first_name` varchar(256) NOT NULL,  `last_name` varchar(256) NOT NULL,  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `last_modified` datetime DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_auth` (  `user_id` int NOT NULL,  `password` varchar(256) DEFAULT NULL,  `OTP_secret` json DEFAULT NULL,  `initialization_token` json DEFAULT NULL,  `authentication_attempts` tinyint(1) NOT NULL DEFAULT '0',  `locked` tinyint(1) NOT NULL DEFAULT '1') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ALTER TABLE `agents`  ADD PRIMARY KEY (`id`),  ADD KEY `added_by` (`added_by`);
ALTER TABLE `audit`  ADD PRIMARY KEY (`id`),  ADD KEY `user_id` (`user_id`);
ALTER TABLE `jobs`  ADD PRIMARY KEY (`id`),  ADD KEY `agent_id` (`agent_id`),  ADD KEY `created_by` (`created_by`);
ALTER TABLE `job_output`  ADD UNIQUE KEY `job_id` (`job_id`);
ALTER TABLE `permissions`  ADD PRIMARY KEY (`id`);
ALTER TABLE `permission_lookup`  ADD KEY `role_id` (`role_id`,`permission_id`),  ADD KEY `permission_id` (`permission_id`);
ALTER TABLE `roles`  ADD PRIMARY KEY (`id`);
ALTER TABLE `role_lookup`  ADD KEY `user_id` (`user_id`,`role_id`),  ADD KEY `role_id` (`role_id`);
ALTER TABLE `users`  ADD PRIMARY KEY (`id`),  ADD UNIQUE KEY `username` (`username`), ADD UNIQUE `email_address` (`email_address`);
ALTER TABLE `user_auth`  ADD UNIQUE KEY `user_id` (`user_id`);
ALTER TABLE `agents`  MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `audit`  MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `jobs`  MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `permissions`  MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `roles`  MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `users`  MODIFY `id` int NOT NULL AUTO_INCREMENT;
ALTER TABLE `agents`  ADD CONSTRAINT `agents_ibfk_1` FOREIGN KEY (`added_by`) REFERENCES `users` (`id`);
ALTER TABLE `audit`  ADD CONSTRAINT `audit_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `jobs`  ADD CONSTRAINT `jobs_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),  ADD CONSTRAINT `jobs_ibfk_2` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`);
ALTER TABLE `job_output`  ADD CONSTRAINT `job_output_ibfk_1` FOREIGN KEY (`job_id`) REFERENCES `jobs` (`id`);
ALTER TABLE `permission_lookup`  ADD CONSTRAINT `permission_lookup_ibfk_1` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`),  ADD CONSTRAINT `permission_lookup_ibfk_2` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`);
ALTER TABLE `role_lookup`  ADD CONSTRAINT `role_lookup_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),  ADD CONSTRAINT `role_lookup_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `user_auth`  ADD CONSTRAINT `user_auth_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
COMMIT;
SET FOREIGN_KEY_CHECKS = 1;